#!/usr/bin/kermit

set port /dev/pts/5
set speed 38400
set carrier-watch off
#set handshake none
set flow-control none
set prefixing all

echo {loading uImage}
PAUSE 1

#OUTPUT loadb ${loadaddr} 38400\{13}
#OUTPUT loadb 0x60000000 38400\{13}
#send images/hola.txt
#INPUT 180 {\{13}\{10}STM32F429-DISCO> }
#IF FAIL STOP 1 INPUT timeout

#echo {running kernel}
#PAUSE 1
#OUTPUT run addip; bootm\{13}

c
